version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "stone_go"
      POSTGRES_USER: "stone_go"
      POSTGRES_DB: "stone_go"
    ports:
      - "15432:5432"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pro.vitoralmeida@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
